development:
  secret_key_base: 104e4f8072ff65128e391823bbea412825843831224962cdcb8852eb7a2622a941e6e6537eb0a03b07eec96097cc876af08aa5cc776d51f210a4815ddb8434e4
  aws_access_key: <%= ENV["ABC_SANDBOX_AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["ABC_SANDBOX_AWS_SECRET_KEY"] %>

test:
  secret_key_base: cc7d576841aeb78013fec7d29adca8c7a8b6c0b992837c81798f324791ff930ec5eb36feeb35cbc4e45f9cc1f49d9d3aaafb8178191a2c18c909da69770d026e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["ABC_SANDBOX_AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["ABC_SANDBOX_AWS_SECRET_KEY"] %>
